// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wynn.Booking.Infrastructure.Persistence;

#nullable disable

namespace Wynn.Booking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260603020000_AddMembersTable")]
    partial class AddMembersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model captured in BookingDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
